Create android deployment guide. This document includes jenkins setup…
Hipo/mobile-team-guidelines pull request #11
Opened 2018-09-07 15:00 UTC by artizco

…, tryouts setup, app setup and sending release.

2018-09-14 09:38 UTC, ahmetmentes requested changes

2018-09-14 09:38 UTC, ahmetmentes commented on Android-Deployment-Guide.md
> +- Multiple app release at once: **1.0.0-1&1.0.1-1**
One minor note, I know I suggested the '&' character here but I tried and git doesn't allow it in the tag name, we can change it with '@'. I tried lots of characters here :D

2018-09-14 15:19 UTC, yasin-ce commented on Android-Deployment-Guide.md
> +- Multiple app release at once: **1.0.0-1&1.0.1-1**
As we talked at huddle I updated the tag format

2018-09-19 12:44 UTC, ahmetmentes approved these changes

2018-09-19 14:42 UTC, merged